### ISSUE TITLE
Line.perpindicular() fails

### ISSUE THREAD

**Issue by mcow** [jan-mue/geometer#103]
version = 0.3.4
Python (windows) 3.11.1

This simple case throws `TensorComputationError`:

```
>>> PAIR = [Point(-5, 2), Point(5, 2)]
>>> ll = Line(PAIR)
>>> ll
Line([Point(-5, 2), Point(5, 2)])
>>> ll.perpendicular(Point(0,2))
```

**Comment by jan-mue** [comment]
There‘s a problem with the way you create the line object. See my comment in #104
