### ISSUE TITLE
Line.contains() fails

### ISSUE THREAD

**Issue by mcow** [jan-mue/geometer#104]
version = 0.3.4
Python (windows) 3.11.1

This simple case throws `TensorComputationError`:
```
>>> PAIR = [Point(-5, 2), Point(5, 2)]
>>> ll = Line(PAIR)
>>> ll
Line([Point(-5, 2), Point(5, 2)])
>>> ll.contains(Point(0, 6))
```

**Comment by jan-mue** [comment]
The `Line` class takes either two points as parameters or an array/list containing the components of the vector in n+1 dimensions that defines the line in n-dimensional projective space.
So, you could change your code to this:
```python
PAIR = [Point(-5, 2), Point(5, 2)]
>>> ll = Line(*PAIR)
>>> ll
Line(Point(-5, 2), Point(5, 2))
>>> ll.contains(Point(0, 6))
```
