### ISSUE TITLE
release with updated numpy dependency version

### ISSUE THREAD

**Issue by xrmx** [jan-mue/geometer#117]
Hello, we would like to use geometer in pyscript and the latest release candidate have bumped pyodide version to 0.22.1 which ships an updated 1.23.5 numpy version. Latest released geometer requires a <1.23 numpy so it cannot be installed anymore. Any chance you can release on pypi a new version please? Thanks!

**Comment by jan-mue** [comment]
I've uploaded a new release with the upper bound for numpy removed.

**Comment by xrmx** [comment]
Thanks a lot!
