### ISSUE TITLE
[clarification] What are the intended uses of this package?

### ISSUE THREAD

**Issue by ReblochonMasque** [jan-mue/geometer#20]
Hello Jan,

I spent some time to read through the code, and the docs of **geometer**. I installed it & I am trying and exploring now. I wanted to ask you what is the intent for this package, and for what uses did you built it?

My love of geometry drove me towards projective geometry, and I am learning about it. My interests also lay with interactive geometry, and I was wondering if, and how I could use **geometer** for this purpose.

Thank you
Cheers!

**Comment by jan-mue** [comment]
Hi, thank you for your interest in the project! I originally built the package for educational purposes, i.e. to help me understand how to implement the things I learned about projective geometry in my theoretical courses ([1](https://www-m10.ma.tum.de/bin/view/Lehre/SS18/PG1SS18/WebHome) and [2](https://www-m10.ma.tum.de/bin/view/Lehre/WS1819/ProjectiveGeometry2WS1818)). I published the package in the hope that someone can find a good use case for the elegant mathematical tools that are implemented in it. When I skimmed through some books on computer vision, I found that some of the things that I implemented might also be useful in that field (for epipolar geometry, camera calibration etc). Of course you could also use it for any other application, where the mathematical tools work. At my university projective geometry is often used for dynamic/interactive geometry, so I’m sure that would be a good application.
