### ISSUE TITLE
Issues with small angle calculations

### ISSUE THREAD

**Issue by DuaneKaufman** [jan-mue/geometer#22]
Dear Sirs,
I have run into an issue when trying to calculate small angles using geometer. The geometry I am setting up is basically two intersecting lines, and the for loop is changing the geometry so the two lines are both rotating (as position in front of vehicle grows larger), and the angle between them is growing smaller.
At a certain point, the angle between the lines goes from a (small) positive value, to zero (around 16.6m in front of the vehicle). I think there may be precision lost in the array calculations done calculating the angle:

PS Z:\my_python\GeometerTest> c:\python37\python.exe .\GeometerTest.py
Point on road in front of vehicle 10.0 meters changes image angle by: 0.48873293 degtrees
Point on road in front of vehicle 10.1 meters changes image angle by: 0.47939775 degtrees
Point on road in front of vehicle 10.2 meters changes image angle by: 0.47032307 degtrees
Point on road in front of vehicle 10.3 meters changes image angle by: 0.46149947 degtrees
Point on road in front of vehicle 10.4 meters changes image angle by: 0.45291791 degtrees
Point on road in front of vehicle 10.5 meters changes image angle by: 0.44456978 degtrees
Point on road in front of vehicle 10.6 meters changes image angle by: 0.43644682 degtrees
Point on road in front of vehicle 10.7 meters changes image angle by: 0.42854112 degtrees
Point on road in front of vehicle 10.8 meters changes image angle by: 0.42084514 degtrees
Point on road in front of vehicle 10.9 meters changes image angle by: 0.41335162 degtrees
Point on road in front of vehicle 11.0 meters changes image angle by: 0.40605365 degtrees
Point on road in front of vehicle 11.1 meters changes image angle by: 0.39894456 degtrees
Point on road in front of vehicle 11.2 meters changes image angle by: 0.39201799 degtrees
Point on road in front of vehicle 11.3 meters changes image angle by: 0.38526784 degtrees
Point on road in front of vehicle 11.4 meters changes image angle by: 0.37868825 degtrees
Point on road in front of vehicle 11.5 meters changes image angle by: 0.37227359 degtrees
Point on road in front of vehicle 11.6 meters changes image angle by: 0.36601847 degtrees
Point on road in front of vehicle 11.7 meters changes image angle by: 0.35991771 degtrees
Point on road in front of vehicle 11.8 meters changes image angle by: 0.35396635 degtrees
Point on road in front of vehicle 11.9 meters changes image angle by: 0.34815960 degtrees
Point on road in front of vehicle 12.0 meters changes image angle by: 0.34249288 degtrees
Point on road in front of vehicle 12.1 meters changes image angle by: 0.33696177 degtrees
Point on road in front of vehicle 12.2 meters changes image angle by: 0.33156203 degtrees
Point on road in front of vehicle 12.3 meters changes image angle by: 0.32628959 degtrees
Point on road in front of vehicle 12.4 meters changes image angle by: 0.32114051 degtrees
Point on road in front of vehicle 12.5 meters changes image angle by: 0.31611103 degtrees
Point on road in front of vehicle 12.6 meters changes image angle by: 0.31119751 degtrees
Point on road in front of vehicle 12.7 meters changes image angle by: 0.30639645 degtrees
Point on road in front of vehicle 12.8 meters changes image angle by: 0.30170449 degtrees
Point on road in front of vehicle 12.9 meters changes image angle by: 0.29711837 degtrees
Point on road in front of vehicle 13.0 meters changes image angle by: 0.29263497 degtrees
Point on road in front of vehicle 13.1 meters changes image angle by: 0.28825128 degtrees
Point on road in front of vehicle 13.2 meters changes image angle by: 0.28396440 degtrees
Point on road in front of vehicle 13.3 meters changes image angle by: 0.27977151 degtrees
Point on road in front of vehicle 13.4 meters changes image angle by: 0.27566993 degtrees
Point on road in front of vehicle 13.5 meters changes image angle by: 0.27165704 degtrees
Point on road in front of vehicle 13.6 meters changes image angle by: 0.26773033 degtrees
Point on road in front of vehicle 13.7 meters changes image angle by: 0.26388737 degtrees
Point on road in front of vehicle 13.8 meters changes image angle by: 0.26012582 degtrees
Point on road in front of vehicle 13.9 meters changes image angle by: 0.25644342 degtrees
Point on road in front of vehicle 14.0 meters changes image angle by: 0.25283798 degtrees
Point on road in front of vehicle 14.1 meters changes image angle by: 0.24930740 degtrees
Point on road in front of vehicle 14.2 meters changes image angle by: 0.24584962 degtrees
Point on road in front of vehicle 14.3 meters changes image angle by: 0.24246269 degtrees
Point on road in front of vehicle 14.4 meters changes image angle by: 0.23914469 degtrees
Point on road in front of vehicle 14.5 meters changes image angle by: 0.23589378 degtrees
Point on road in front of vehicle 14.6 meters changes image angle by: 0.23270818 degtrees
Point on road in front of vehicle 14.7 meters changes image angle by: 0.22958617 degtrees
Point on road in front of vehicle 14.8 meters changes image angle by: 0.22652608 degtrees
Point on road in front of vehicle 14.9 meters changes image angle by: 0.22352630 degtrees
Point on road in front of vehicle 15.0 meters changes image angle by: 0.22058526 degtrees
Point on road in front of vehicle 15.1 meters changes image angle by: 0.21770145 degtrees
Point on road in front of vehicle 15.2 meters changes image angle by: 0.21487340 degtrees
Point on road in front of vehicle 15.3 meters changes image angle by: 0.21209971 degtrees
Point on road in front of vehicle 15.4 meters changes image angle by: 0.20937899 degtrees
Point on road in front of vehicle 15.5 meters changes image angle by: 0.20670992 degtrees
Point on road in front of vehicle 15.6 meters changes image angle by: 0.20409120 degtrees
Point on road in front of vehicle 15.7 meters changes image angle by: 0.20152159 degtrees
Point on road in front of vehicle 15.8 meters changes image angle by: 0.19899987 degtrees
Point on road in front of vehicle 15.9 meters changes image angle by: 0.19652487 degtrees
Point on road in front of vehicle 16.0 meters changes image angle by: 0.19409545 degtrees
Point on road in front of vehicle 16.1 meters changes image angle by: 0.19171051 degtrees
Point on road in front of vehicle 16.2 meters changes image angle by: 0.18936897 degtrees
Point on road in front of vehicle 16.3 meters changes image angle by: 0.18706979 degtrees
Point on road in front of vehicle 16.4 meters changes image angle by: 0.18481197 degtrees
Point on road in front of vehicle 16.5 meters changes image angle by: 0.18259452 degtrees
Point on road in front of vehicle 16.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 16.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 16.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 16.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 17.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 18.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 19.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 20.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 21.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 22.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 23.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 24.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 25.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 26.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 27.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 28.9 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.0 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.1 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.2 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.3 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.4 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.5 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.6 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.7 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.8 meters changes image angle by: 0.00000000 degtrees
Point on road in front of vehicle 29.9 meters changes image angle by: 0.00000000 degtrees
PS Z:\my_python\GeometerTest>

Code to generate this output is below:

import geometer
import numpy as np

IlluminatorHeight = 1.41732
IlluminatorLocation = geometer.Point(0, 0, IlluminatorHeight)  # All unit measurements converted to SI and stripped before use in geometry module
LaneMarkingSpacing = 3.5052
# Now introduce motion of vehicle
VehicleSpeed = 26.8224
WP_BP_FrameRate = 70
RoadMotionDistance = VehicleSpeed / WP_BP_FrameRate
StartLanePoint = 10
for StartLanePoint in np.arange(10, 30, .1):
	StartLanePointLocation = geometer.Point(geometer.Point(LaneMarkingSpacing/2, StartLanePoint, 0))
	StartLanePointRay = geometer.Line(IlluminatorLocation, StartLanePointLocation)
	EndLanePoint = StartLanePoint - RoadMotionDistance  # Road point gets closer to car
	EndLanePointLocation = geometer.Point(geometer.Point(LaneMarkingSpacing/2, EndLanePoint, 0))
	EndLanePointRay = geometer.Line(IlluminatorLocation, EndLanePointLocation)
	print("Point on road in front of vehicle {0:1.1f} meters changes image angle by: {1:1.8f} degtrees".format(StartLanePoint, np.rad2deg(np.real(geometer.angle(StartLanePointRay, EndLanePointRay)))))

Sincerely,
Duane

**Comment by jan-mue** [comment]
Hi Duane,

this issue is caused by a shortcut in the angle calculation that checks if two lines are identical and returns 0 in that case. I changed the tolerances for the equality of two points/lines in version 0.2 of the package and your problem should no longer occur (after executing `pip install geometer -U`).
If you have to adjust the accuracy of this or other calculations, there are now two parameters in the geometer.base module that control the tolerance used when checking equality.

**Comment by DuaneKaufman** [comment]
Dear Jan, 

Excellent news. I thought it might be something like that, but was not familiar enough with the codebase to dig into it. I implemented an alternate calculation method, and can check this change against it. 

I really like your package, and even purchased the book you mentioned on the topic. 

Sincerely, 
Duane 

----- Original Message -----
