### ISSUE TITLE
Rectangle vertex order matters

### ISSUE THREAD

**Issue by manuel-delverme** [jan-mue/geometer#40]
I'm not sure if it's intended but:

```
geometer.Rectangle(
    np.array([0., 0., 1.]),
    np.array([0., 1., 1.]),
    np.array([1., 1., 1.]),
    np.array([1., 0., 1.]),
).area
>> 1.
```

```
geometer.Rectangle(
    np.array([0., 0., 1.]),
    np.array([0., 1., 1.]),
    np.array([1., 0., 1.]),
    np.array([1., 1., 1.]),
).area
>> 0.
```

**Comment by jan-mue** [comment]
This is expected as the area is calculated as the sum of the oriented areas of the triangles formed by the vertices. If the vertices in one of these triangles are given in clockwise order, the area will be negative and in your case this sums up to zero with the second triangle in the rectangle. It shouldn't matter whether the vertices of the whole rectangle are ordered counter-clockwise or clockwise as the `area` property only contains the absolute value of the oriented area but the vertices must be ordered in one of these ways.
I will add a remark in the docstring of the `Polygon` class to clarify this.
