### ISSUE TITLE
Intersection of line and cylinder

### ISSUE THREAD

**Issue by pauljurczak** [jan-mue/geometer#44]
Is intersection of line and cylinder implemented? I tried this:
```
c = Cylinder()
l = Line(Point(2, 2, 2), Point(3, 3, 3))
print(l.meet(c))
```
without success.

**Comment by jan-mue** [comment]
It is implemented but you have to use the `intersect` method of the Quadric/Cylinder class which returns a list of points instead of the single point/subspace that `meet` returns. This code should work:
```python
c = Cylinder()
l = Line(Point(2, 2, 2), Point(3, 3, 3))
print(c.intersect(l))
```
I'll close this issue but please let me know if you have any more questions.

**Comment by pauljurczak** [comment]
Thank you. One more question: what is the recommended test for a point in infinity, which is returned when there is no intersection?

**Comment by jan-mue** [comment]
> Thank you. One more question: what is the recommended test for a point in infinity, which is returned when there is no intersection?

Points at infinity are exactly those that have a zero in their last coordinate. For convenience I added the property `isinf` to the `Point` class that checks if the last coordinate is close to zero.

**Comment by pauljurczak** [comment]
Which is the last coordinate? This snippet:
```
c = Cylinder()
l = Line(Point(3, 3, 2), Point(3, 3, 3))
print(c.intersect(l))
```
produces:
```
[Point(0j, 0j, (-0.7276068751089989+0.6859943405700353j)) at Infinity]
```
with non-zero last coordinate.

**Comment by jan-mue** [comment]
> Which is the last coordinate? This snippet:
> 
> ```
> c = Cylinder()
> l = Line(Point(3, 3, 2), Point(3, 3, 3))
> print(c.intersect(l))
> ```
> 
> produces:
> 
> ```
> [Point(0j, 0j, (-0.7276068751089989+0.6859943405700353j)) at Infinity]
> ```
> 
> with non-zero last coordinate.

The last coordinate is not shown in the standard string representation of a point. Instead "at Infinity" is added when it is close to zero. You can see all the homogeneous coordinates like this: `print(c.intersect(l)[0].array)`. You can also directly access the last coordinate like this: `print(c.intersect(l)[0][-1])`.
