### ISSUE TITLE
numerical instability

### ISSUE THREAD

**Issue by coproc** [jan-mue/geometer#51]
>>> from geometer import Point, dist
    >>> p1 = Point(100.0, 0.0)
    >>> p2 = Point(101.0, 0.0)
    >>> p1 == p2
    True
    >>> dist(p1, p2)
    0

**Comment by jan-mue** [comment]
Thanks for reporting this. I’m looking into it. The issue seems to be the `is_multiple` function.

**Comment by jan-mue** [comment]
This is fixed in version 0.3.1
