### ISSUE TITLE
another numerical instability

### ISSUE THREAD

**Issue by coproc** [jan-mue/geometer#55]
I have run into several numerical instabilities when doing chained computations (mainly intersections). One of the problems is that the coordinates of points are not normalized automatically. Reconstructing objects from points with normalized coordinates after each intersection helps a lot. But in the following case the normalizations did not help:

    a = 100.
    p1 = Point(0., 0.)
    p2 = Point(a,  0.)
    p3 = Point(a,  a)
    p4 = Point(0., a)
    square = Polygon(p1,p2,p3,p4)
    line1 = Line(p3,p4)
    print(square.intersect(line1))

gives:

    ...\lib\site-packages\geometer\point.py:95: RuntimeWarning: invalid value encountered in true_divide
      result.array = result.array / np.max(np.abs(result.array), axis=axes, keepdims=True)
    [Point(100.0, 100.0), Point(-0.0, 100.0)]

Ok, one can live with that warning; the result is correct. But altering the coordinates of the line points a little

    EPS = 1e-6
    line2 = Line(Point(a, a-EPS), Point(0, a+EPS))
    print(square.intersect(line2))

gives an intersection with three points:

    [Point(100.0, 99.99999899999999), Point(49.99999955908597, 100.0), Point(-0.0, 100.00000099999998)]

Here the additional code for correcting the result is a bit more involved.

**Comment by jan-mue** [comment]
By default the result of `meet` or `join` is actually normalized. This means that the result of the `intersect` method of Segment or Polygon classes is normalized, too.

The issue here seem to be the tolerance parameters used in the `intersect` method. By default the tolerance is 1e-8 for the `contains` method of a line segment which is too large to recognize that (0, 100+1e-6) is not contained in the segment from (0, 0) to (0, 100).

I will try to adjust these parameters and make them more configurable.

**Comment by coproc** [comment]
> By default the result of `meet` or `join` is actually normalized. This means that the result of the `intersect` method of Segment or Polygon classes is normalized, too.

    from geometer import Point, Segment
    p1 = Point(0., 0.)
    p2 = Point(10., 0.)
    p3 = Point(1., 1.)
    ps, = Segment(p1,p2).intersect(Segment(p2,p3))
    ps.array

gives `array([1. , 0. , 0.1])`. After normalization I would expect that the third array element is `1.0`.

**Comment by coproc** [comment]
An even stranger source of non-normalized points is mirroring:

    Line(p1,p2).mirror(p3)

correctly gives `Point(1.0, -1.0)`. But its internal representation involves complex numbers:

    Line(p1,p2).mirror(p3).array

gives `array([0.+1.j, 0.-1.j, 0.+1.j])`.

**Comment by coproc** [comment]
> The issue here seem to be the tolerance parameters used in the `intersect` method. By default the tolerance is 1e-8 for the `contains` method of a line segment which is too large to recognize that (0, 100+1e-6) is not contained in the segment from (0, 0) to (0, 100).
> 
> I will try to adjust these parameters and make them more configurable.

Hm, I doubt that this will result in a 100% correct algorithm: although this fix will work most of the time, I would expect corner cases with the same problem. For a 100% correct algorithm I would check for the special case of intersecting at (close to) a vertex.

**Comment by jan-mue** [comment]
The arrays behind points/lines/planes are normalized by the maximum absolute value of all elements. This avoids getting really large numbers after calculating several dot products in a row. To get the actual normalized/de-homogenized coordinates of a point you can use the `normalized_array` property.

Because the mirroring operation uses some complex points in the background it‘s totally expected that the underlying arrays might become complex but again the `normalized_array` properly should give you the real normalized result that you expect.

**Comment by jan-mue** [comment]
> > The issue here seem to be the tolerance parameters used in the `intersect` method. By default the tolerance is 1e-8 for the `contains` method of a line segment which is too large to recognize that (0, 100+1e-6) is not contained in the segment from (0, 0) to (0, 100).
> > I will try to adjust these parameters and make them more configurable.
> 
> Hm, I doubt that this will result in a 100% correct algorithm: although this fix will work most of the time, I would expect corner cases with the same problem. For a 100% correct algorithm I would check for the special case of intersecting at (close to) a vertex.

I will try some extreme cases to see if it helps to check whether a point of intersection is almost equal to a vertex, but then this check only has a certain precision, too. It will never be 100% correct as long as these computations are done numerically.

**Comment by coproc** [comment]
> The arrays behind points/lines/planes are normalized by the maximum absolute value of all elements. This avoids getting really large numbers after calculating several dot products in a row. To get the actual normalized/de-homogenized coordinates of a point you can use the `normalized_array` property.
> 
> Because the mirroring operation uses some complex points in the background it‘s totally expected that the underlying arrays might become complex but again the `normalized_array` properly should give you the real normalized result that you expect.

My observation was: if doing chained computations with these non-normalized arrays, one runs quickly into wrong results (e.g. normalized coordinates are not real any more). So in my application I had to explicitely force normalization after each computation step (by replacing resulting points with points with normalized coordinates).

**Comment by coproc** [comment]
> I will try some extreme cases to see if it helps to check whether a point of intersection is almost equal to a vertex, but then this check only has a certain precision, too. It will never be 100% correct as long as these computations are done numerically.

Sure, there will be rounding errors. With 100% correct I mean a plausible result (within the numerical tolerance), e.g. when intersecting a convex polygon with a line there should never be 3 or more intersection points. Maybe "robust implementation" is a more appropriate wording.

**Comment by coproc** [comment]
I want to propose the following solution for a robust intersection of polygon with a line:
* for each edge compute the intersection of its carrier line with the given line and also the line parameter `t` of this intersection (`t = 0` for the starting point, `t = 1` for the end point of the edge)
* if for an edge we have `t == 1` and for the following edge `t == 0` then the line goes throught the common vertex and we want to have only one of the corresponding intersection points
* if for an edge we have `t == 1` and for the edge following the following edge we have `t == 0` the the line runs along the edge in between and we do not want to have the intersection point with the line in between.
* Finally there should only remain at most two edges with a line parameter of its intersection point in the range `[0, 1]`.

    edgeLineIntersections_p = [edge._line.intersect(line) for edge in poly.edges]
    edgeLineIntersections_t = [edge.lineParam(p) for edge,p in zip(poly.edges,edgeLineIntersections_p]
    for tIdx,t in enumerate(edgeLineIntersections_t):
      if abs(t-1) <= tol:
        if abs(edgeLineIntersections_t[(tIdx+1)%n])  <= tol:
          edgeLineIntersections_t[tIdx] = -1 # invalidate t
        elif abs(edgeLineIntersections_t[(tIdx+2)%n])  <= tol:
          edgeLineIntersections_t[(tIdx+1)%n] = -1 # invalidate t
    polyIntersections = [p for p,t in zip(edgeLineIntersections_p,edgeLineIntersections_t) if -tol <= t <= 1+tol]

**Comment by jan-mue** [comment]
I've made two more changes in version 0.3.3 and 0.3.4 that might help with these numerical instability issues:

- The `contains` method of a `Segment` instance now uses a less complicated calculation that should eliminate some amount of numerical errors introduced there.
- The normalization after a join/meet operation now only changes the exponent of the internal floating point representations thus eliminating any numerical errors introduced by the division that was previously used.

Please let me know if these changes help in your case.

One problem I see with your proposal is that I can't think of a way of calculating the line parameters of the points of intersection points in a way that's more numerically stable than what is currently done with the cross ratio. You're of course always welcome to open a PR.
